### ISSUE TITLE
Doesn't find audio files

### ISSUE THREAD

**Issue by SkidCity** [morrolinux/mpradio-remote#1]
Hello, the app doesn't find my audio files. I can't seem to find where to put them. In what directory should i put my audio files? 
Thanks.

**Comment by morrolinux** [comment]
Hello, the app is a remote for the Pi. 
you can copy all of your music into a usb stick (fat32 partitioned) and boot the pi.
You'll see your files via the app, and you'll be able to play them.
Otherwise if you just wanna play the songs from your smartphone, you're supposed to connect to the Pi via bluetooth audio.

**Comment by SkidCity** [comment]
So i can play audio from my phone without the app? Tried that but i just get static. Do i need to configure it for that or?

**Comment by morrolinux** [comment]
Have you ever used a Bluetooth speaker?

**Comment by SkidCity** [comment]
Yes i have, tried the same thing here but it doesn't work.

**Comment by morrolinux** [comment]
Yeah sorry about that.. the project is currently suspended because of my thigh schedule (in life).
It used to work a while ago, but each time a system component mpradio relies on changes implementation, mpradio (obviously) breaks. It would need constant maintenance in adjusting it to the changes been made. That's much time consuming, and I can't afford it now.
I did publish some full dd images of previous and latest working releases, you could test on those, it should/could work :)
